#!/bin/bash

logger "invoking $(realpath -s $0)"

I3SOCK=$(i3 --get-socketpat)
xrandr --output DP1 --primary
i3-msg '[workspace="^(1|3|5)"] move workspace to output DP1;'
i3-msg '[workspace="^(2|4|6)"] move workspace to output eDP1;'
polybar-msg cmd restart

logger "finished $(realpath -s $0)"